name: first workflow
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  jobtest:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "hello world"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
